export class PropertyOptions {
  public static readonly BEDS = [
    { value: "0", label: "Zero" },
    { value: "1", label: "One" },
    { value: "2", label: "Two" },
    { value: "3", label: "Three" },
    { value: "4", label: "Four" },
    { value: "5", label: "Five" },
    { value: "6", label: "Six" },
    { value: "7", label: "Seven" },
    { value: "8", label: "Eight" },
    { value: "9", label: "Nine" },
    { value: "10", label: "Ten" },
    { value: "11", label: "Eleven" },
    { value: "12", label: "Twelve" },
    { value: "13", label: "Thirteen" },
    { value: "14", label: "Forteen" },
    { value: "15", label: "Fifteen" },
    { value: "16", label: "Sixteen" },
    { value: "17", label: "Seventeen" },
    { value: "18", label: "Eighteen" },
    { value: "19", label: "Nineteen" },
    { value: "20", label: "Twenty" },
  ];

  public static readonly BATHS = [
    { value: "0", label: "Zero" },
    { value: "1", label: "One" },
    { value: "1.5", label: "One & ½" },
    { value: "2", label: "Two" },
    { value: "2.5", label: "Two & ½" },
    { value: "3", label: "Three" },
    { value: "3.5", label: "Three & ½" },
    { value: "4", label: "Four" },
    { value: "4.5", label: "Four & ½" },
    { value: "5", label: "Five" },
    { value: "5.5", label: "Five & ½" },
    { value: "6", label: "Six" },
    { value: "6.5", label: "Six & ½" },
    { value: "7", label: "Seven" },
    { value: "7.5", label: "Seven & ½" },
    { value: "8", label: "Eight" },
    { value: "8.5", label: "Eight & ½" },
    { value: "9", label: "Nine" },
    { value: "9.5", label: "Nine & ½" },
    { value: "10", label: "Ten" },
    { value: "10.5", label: "Ten & ½" },
    { value: "11", label: "Eleven" },
    { value: "11.5", label: "Eleven & ½" },
    { value: "12", label: "Twelve" },
    { value: "12.5", label: "Twelve & ½" },
    { value: "13", label: "Thirteen" },
    { value: "13.5", label: "Thirteen & ½" },
    { value: "14", label: "Forteen" },
    { value: "14.5", label: "Forteen & ½" },
    { value: "15", label: "Fifteen" },
    { value: "15.5", label: "Fifteen & ½" },
    { value: "16", label: "Sixteen" },
    { value: "16.5", label: "Sixteen & ½" },
    { value: "17", label: "Seventeen" },
    { value: "17.5", label: "Seventeen & ½" },
    { value: "18", label: "Eighteen" },
    { value: "18.5", label: "Eighteen & ½" },
    { value: "19", label: "Nineteen" },
    { value: "19.5", label: "Nineteen & ½" },
    { value: "20", label: "Twenty" },
  ];

  public static readonly YES_NO = [
    { value: "yes", label: "Yes" },
    { value: "no", label: "No" },
  ];

  public static readonly LEASE_TERM = [
    { value: "day", label: "Day" },
    { value: "week", label: "Week" },
    { value: "month", label: "Month" },
    { value: "year", label: "Year" },
  ];

  public static readonly SPACE_TYPE = [
    { value: "unit", label: "Unit" },
    { value: "dwelling", label: "Dwelling" },
  ];

  public static readonly BILLED_BY = [
    { value: "hour", label: "Hour" },
    { value: "day", label: "Day" },
  ];

  public static readonly HOURS = [
    { value: "00:00:00", label: "12 AM" },
    { value: "01:00:00", label: "1 AM" },
    { value: "02:00:00", label: "2 AM" },
    { value: "03:00:00", label: "3 AM" },
    { value: "04:00:00", label: "4 AM" },
    { value: "05:00:00", label: "5 AM" },
    { value: "06:00:00", label: "6 AM" },
    { value: "07:00:00", label: "7 AM" },
    { value: "08:00:00", label: "8 AM" },
    { value: "09:00:00", label: "9 AM" },
    { value: "10:00:00", label: "10 AM" },
    { value: "11:00:00", label: "11 AM" },
    { value: "12:00:00", label: "12 PM" },
    { value: "13:00:00", label: "1 PM" },
    { value: "14:00:00", label: "2 PM" },
    { value: "15:00:00", label: "3 PM" },
    { value: "16:00:00", label: "4 PM" },
    { value: "17:00:00", label: "5 PM" },
    { value: "18:00:00", label: "6 PM" },
    { value: "19:00:00", label: "7 PM" },
    { value: "20:00:00", label: "8 PM" },
    { value: "21:00:00", label: "9 PM" },
    { value: "22:00:00", label: "10 PM" },
    { value: "23:00:00", label: "11 PM" },
  ];
}
